name: End-to-end tests
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          REACT_APP_POCKETBASE_TEST_URL: https://taska-test.liara.run
        with:
          start: npm start
      - uses: actions/upload-artifact@v4
        
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
